AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  csp-report-collector

  Collects Content Security Policy violation reports from browsers
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LogReportFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: log-report/
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlesshttpapi
          Properties:
            Path: /_/report/csp
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for the default stage for Hello World function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/_/report/csp"
  LogReportFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt LogReportFunction.Arn
  LogReportFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LogReportFunctionRole.Arn
